### ISSUE TITLE
Install completed, don't see the UI?

### ISSUE THREAD

**Issue by notflip** [bcc-code/directus-schema-sync#16]
I followed the steps, and got the extension loaded in my Directus instance. Where can I find the extension (UI)?
Thanks!

**Comment by u12206050** [comment]
It doesn't have a UI only json config and cli commands. Just curious what UI do you expect it to have?

**Comment by u12206050** [comment]
Ah I understand, that refers to the collections and fields that you can setup, if you have it setup to sync BOTH import and and export or just export, then whenever you add a new field to a collection via the UI then that field is added to the schema file, without you needing to manually run snapshot cli command.
The same will go for other data that you then have setup in the config.
I can see the misunderstanding though. Maybe one day I'll get around to making a UI

**Comment by notflip** [comment]
Thanks for the info and the work on this! I will test all of this out this weekend.
