### ISSUE TITLE
Big directus_permissions export due to duplicates

### ISSUE THREAD

**Issue by adelinn** [bcc-code/directus-schema-sync#22]
### Describe the Bug

Export of directus_permissions sometimes gets really big due to many duplicates.

### To Reproduce

To be determined.
It happened to me on a fresh instance.

### Version

1.6.2

### Installed Extension Via

NPM Custom

**Comment by u12206050** [comment]
The latest version if you use the following config will remove duplicates upon import.

```
	directus_permissions: {
		watch: ['permissions', 'collections', 'fields'],
		excludeFields: ['id'],
		getKey: (o) => `${o.role ?? 'public'}-${o.collection}--${o.action}`,
		query: {
			sort: ['role', 'collection', 'action'],
		},
	},
```
