### ISSUE TITLE
Impossible to run the install command in a new project

### ISSUE THREAD

**Issue by karamokoisrael** [bcc-code/directus-schema-sync#25]
### Describe the Bug

When I try running the install command, I get the following error message => error: unknown command 'schema-sync'

### To Reproduce

CREATE a new directus project

ADD directus-extension-schema-sync package

RUN `npx directus schema-sync install`

### Version

10.9.0

### Installed Extension Via

NPM Custom

**Comment by jperestrelo** [comment]
Im also having the same issue

**Comment by yanmorinokamca** [comment]
With an existing directus version, I had to run `directus database migrate:up` so that schema-sync show up in the cli commands.
Check with npx directus help  to see if the commands show up.

**Comment by u12206050** [comment]
Seems like this has been resolved, although it would be interesting to know why the `npx directus schema-sync install` didn't work, as that basically calls the migrate command within itself. Did you get any errors?

**Comment by karamokoisrael** [comment]
> Seems like this has been resolved, although it would be interesting to know why the `npx directus schema-sync install` didn't work, as that basically calls the migrate command within itself. Did you get any errors?

Thank you, that's what I've done and it works.
