### ISSUE TITLE
Role sync?

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [bcc-code/directus-schema-sync#37]
### Describe the Improvement

Is it possible to sync the roles? As I found there is a way to synchronize permissons.

**Comment by martin-braun** [comment]
Sure there is. Have you inspected the configuration carefully?

It's part of the default configuration in `directus_config.js`:

```javascript
export const syncDirectusCollections = {
  directus_roles: {
    watch: ["roles"],
  },
  directus_permissions: {
    watch: ["permissions", "collections", "fields"],
    excludeFields: ["id"],
    getKey: (o) => `${o.role ?? "public"}-${o.collection}--${o.action}`,
    query: {
      sort: ["role", "collection", "action"],
    },
  },
}
```

**Comment by martin-braun** [comment]
@u12206050 Glad that you've answered me on this one, would've fall into that pitfall in the future. Since I only init with admin users I guess it wasn't a problem.
