### ISSUE TITLE
Ability to see if there were changes during an import

### ISSUE THREAD

**Issue by martin-braun** [bcc-code/directus-schema-sync#40]
### Describe the Improvement

I'm using Ansible for my deployment. A crucial feature of Ansible is the ability to have a `changed_when` expression for tasks, so I'm looking for a way to reliably detect if an import actually changed anything. My first guess was the `mv_hash` in the directus settings would change, so that I could have a shell task that executes this:

```sh
current="$(psql -XAtc 'SELECT mv_hash FROM directus_settings LIMIT 1;')"
next="$(cat 'schema-sync/hash.txt' | cut -d '@' -f -1)"
printf "Current: $current\nNext: $next"
test "$current" = "$next"
```

A non-zero return code would indicate the next import will change my schema and data, but apparently this is not the case, the `mv_hash` doesn't match the contents of the `hash.txt` after import, so I guess I was wrong on that.

I also inspected the output of `npx directus schema-sync import`, but nothing indicates that changes where made, so I couldn't even parse `stdout`.

Could we please do something about it? I need a reliable way to see if changes where made.

**Comment by u12206050** [comment]
I'm assuming you are talking about changes to the schema right? Since there is some logging indicating updates/changes done to data.

**Comment by martin-braun** [comment]
@u12206050 Schema and data on `schema-sync import` and just the schema on `schema-sync import-schema` respectively. I started testing this only after changing the schema, so the logging of data changes went over my head. Is this logged to `stdout`?

**Comment by martin-braun** [comment]
I just re-test `schema-sync import --merge` and all it prints is `INFO: Importing everything from: ..../schema-sync/data` and this info also prints when I re-run the command despite there being no new data to import.

**Comment by u12206050** [comment]
Closing this as not planned

**Comment by martin-braun** [comment]
@u12206050 I respect your decision, after all this is a very nuanced problem, although I have two questions:

1. Would you still be interested in a PR to address this?
2. Could you still give some thoughts on how I could detect schema and data changes?

Thanks.

**Comment by u12206050** [comment]
Sure a PR is welcome.

Neither schema nor data changes should be too hard to compare and print of the diff. The main problem I see is displaying the diff in a reasonable understanding way.

**Comment by martin-braun** [comment]
@u12206050 maybe a verbose flag could help, it could print much more without disrupting the default behavior?

**Comment by u12206050** [comment]
Yes that should be very doable. I believe in the code where we are comparing db rows to file rows would be the ideal place for this. Displaying sensible output including schema changes might still be hard though.
