### ISSUE TITLE
Deleted fields or collections still exist in sync folder

### ISSUE THREAD

**Issue by yipivan** [bcc-code/directus-schema-sync#43]
### Describe the Bug

when I delete a field or collection from directus, the changes are not exported, that causes we cannot sync delete actions across environments.

### To Reproduce

Just created a collection in directus and do an schema export
then delete the collection and export again, the exported sync files still exists

### Version

2.1.1

### Installed Extension Via

NPM Custom

**Comment by u12206050** [comment]
Seems to only be a problem when deleting the collection, deleting the field does seem to work.
Will need to remove existing schema files before creating new ones in order to fix this issue. It seems to only be an issue when the schema is split into multiple files.

**Comment by yipivan** [comment]
Deleting a field does work on user defined collections, but if you add a field to any system collections then delete it, the sync files wont reflect the delete action.

**Comment by u12206050** [comment]
Fixed https://github.com/bcc-code/directus-schema-sync/releases/tag/v2.1.2
