### ISSUE TITLE
You don't have permission to access field "role" in collection "directus_permissions" or it does not exist. Queried in root.

### ISSUE THREAD

**Issue by martin-braun** [bcc-code/directus-schema-sync#49]
### Describe the Bug

I believe since version 11 of Directus the data model has changed. `directus bootstrap` results in a database where `directus_permissions` has no `role` column anymore, hence exporting or importing with this tool doesn't work anymore.

### To Reproduce

```
npx directus bootstrap # on a fresh instance with a fresh database
directus schema-sync export # throws
```

### Version

3.0.1

### Installed Extension Via

NPM Custom

**Comment by u12206050** [comment]
It still works, although you need to update the `schema-sync/directus_config.js` file with the following first:

Note: Make sure to replace the two existing collections, and then add the others, in this order.
```
…
	directus_roles: {
		watch: ['roles'],
		linkedFields: ['parent'],
		query: {
			sort: ['name'],
		},
	},
	directus_policies: {
		watch: ['policies'],
		query: {
			sort: ['name'],
		},
	},
	directus_permissions: {
		watch: ['permissions', 'collections', 'fields'],
		excludeFields: ['id'],
		getKey: o => `${o.policy}-${o.collection}-${o.action}`,
		query: {
			sort: ['policy', 'collection', 'action'],
		},
	},
	directus_access: {
		watch: ['access'],
		excludeFields: ['id'],
		getKey: o => `${o.role ?? o.user ?? 'public'}-${o.policy}`,
		query: {
			sort: ['role', 'policy'],
			filter: {
				user: { _null: true },
			},
		},
	},
	…
```

**Comment by martin-braun** [comment]
@u12206050 You are absolutely right and I feel a bit embarrassed. I guess it was a little bit late yesterday when I tried to update everything and reimport. 

Obviously, your tool offers all the necessary routines, but it's the `directus_config.js` / `schema.json` that defines the DB's structure and table API. I obviously have to adapt it to the migrations of Directus themselves. It's a bit of a task to work that out, but I guess that inevitable every major version of Directus. 

I love your extension, please keep it up. ❤️
