### ISSUE TITLE
error: unknown command 'schema-sync'

### ISSUE THREAD

**Issue by 8seneca-global** [bcc-code/directus-schema-sync#53]
### Describe the Bug

When i run:  npx directus schema-sync install --force
it throws error: unknown command 'schema-sync'

### To Reproduce

 run:  "npx directus schema-sync install --force" in docker container

### Version

3.0.2

### Installed Extension Via

Docker file

**Comment by cyprian-nziim** [comment]
Hello @8seneca-global you need to first install the package like so:

```
FROM directus/directus:11.2.1

USER root
RUN corepack enable

// Workaround to be able to install extensions with 'node' user, only required in v11.1.1
RUN rm node_modules/.modules.yaml

RUN pnpm install directus-extension-schema-sync


WORKDIR /directus

RUN npx directus schema-sync install --force
```

**Comment by 8seneca-global** [comment]
Thank u for your support but i'm building docker image from directus source with this Dockerfile so it still not work, do u have any idea?

`# syntax=docker/dockerfile:1.4
FROM node:18-alpine AS builder
WORKDIR /directus

ARG TARGETPLATFORM

ENV NODE_OPTIONS=--max-old-space-size=8192

RUN <<EOF
  if [ "$TARGETPLATFORM" = 'linux/arm64' ]; then
  	apk --no-cache add python3 build-base
  	ln -sf /usr/bin/python3 /usr/bin/python
  fi
EOF

COPY package.json .
RUN corepack enable && corepack prepare

COPY pnpm-lock.yaml .
RUN pnpm fetch

COPY . .

RUN pnpm install --recursive --offline --frozen-lockfile \
	&& pnpm install directus-extension-schema-sync -w \
	&& npm_config_workspace_concurrency=1 pnpm run build \
	&& pnpm --filter directus deploy --prod dist \
	&& ls -la dist \
	&& cd dist \
	&& node -e ' const f = "package.json", {name, version, type, exports, bin} = require(`./${f}`), {packageManager} = require(`../${f}`); require("fs").writeFileSync(f, JSON.stringify({name, version, type, exports, bin, packageManager}, null, 2));' \
	&& mkdir -p database extensions uploads

####################################################################################################
## Create Production Image

FROM node:18-alpine AS runtime

RUN npm install --global pm2@5

USER node

WORKDIR /directus

EXPOSE 8055

ENV \
	NODE_ENV="production" \
	NPM_CONFIG_UPDATE_NOTIFIER="false"

COPY --from=builder --chown=node:node /directus/ecosystem.config.cjs .
COPY --from=builder --chown=node:node /directus/dist .

CMD : \
	&& node cli.js bootstrap \
	&& pm2-runtime start ecosystem.config.cjs \
	;
`

**Comment by 8seneca-global** [comment]
nevermind, i fixed it, need to move install part to production image build section, thank u
